# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-02 22:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_program_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image_url',
            field=models.CharField(default=datetime.datetime(2016, 6, 2, 22, 17, 56, 912219, tzinfo=utc), max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='finish_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 2, 22, 18, 1, 46532, tzinfo=utc), verbose_name=b'program finish date'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='program',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 6, 2, 22, 18, 8, 712472, tzinfo=utc), verbose_name=b'program start date'),
            preserve_default=False,
        ),
    ]
