# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 12:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_remove_course_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Category')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='videos.Course')),
            ],
        ),
    ]
