# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 12:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_coursecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='short_id',
            field=models.CharField(default='hadi', max_length=100),
            preserve_default=False,
        ),
    ]
