# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 12:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0009_person_short_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='home_page_url',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='position',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
