# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 12:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_course_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='old_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
