# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0012_program_old_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='finish_date',
            field=models.DateTimeField(null=True, verbose_name=b'program finish date'),
        ),
        migrations.AlterField(
            model_name='program',
            name='start_date',
            field=models.DateTimeField(null=True, verbose_name=b'program start date'),
        ),
    ]
