# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0013_auto_20160603_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='old_id',
            field=models.IntegerField(null=True),
        ),
    ]
