# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-03 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0014_category_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='bg_image_url',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
